// <auto-generated />
using System;
using Bep.Modules.Reporting.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bep.Modules.Reporting.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ReportingDbContext))]
    partial class ReportingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reporting")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bep.Modules.Reporting.Domain.Informe", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AutorSubjectId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("autor_subject_id");

                    b.Property<Guid?>("CampanaId")
                        .HasColumnType("uuid")
                        .HasColumnName("campana_id");

                    b.Property<Guid?>("CentroId")
                        .HasColumnType("uuid")
                        .HasColumnName("centro_id");

                    b.Property<DateTimeOffset>("CreadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("FechaAprobacionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TipoEstudio")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("VersionVigenteNumero")
                        .HasColumnType("integer")
                        .HasColumnName("version_vigente_numero");

                    b.HasKey("Id");

                    b.HasIndex("CampanaId");

                    b.HasIndex("Estado");

                    b.HasIndex("TenantId");

                    b.ToTable("informe", "reporting");
                });

            modelBuilder.Entity("Bep.Modules.Reporting.Domain.Informe", b =>
                {
                    b.OwnsMany("Bep.Modules.Reporting.Domain.Anexo", "Anexos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Descripcion")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<DateTimeOffset>("FechaUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("InformeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ObjectKey")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("object_key");

                            b1.HasKey("Id");

                            b1.HasIndex("InformeId");

                            b1.ToTable("anexo", "reporting");

                            b1.WithOwner()
                                .HasForeignKey("InformeId");
                        });

                    b.OwnsMany("Bep.Modules.Reporting.Domain.ComentarioInterno", "Comentarios", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("AutorSubjectId")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("autor_subject_id");

                            b1.Property<DateTimeOffset>("FechaUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("InformeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Texto")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)");

                            b1.HasKey("Id");

                            b1.HasIndex("InformeId");

                            b1.ToTable("comentario_interno", "reporting");

                            b1.WithOwner()
                                .HasForeignKey("InformeId");
                        });

                    b.OwnsOne("Bep.Modules.Reporting.Domain.PeriodoCubierto", "Periodo", b1 =>
                        {
                            b1.Property<Guid>("InformeId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("Desde")
                                .HasColumnType("date")
                                .HasColumnName("periodo_desde");

                            b1.Property<DateOnly>("Hasta")
                                .HasColumnType("date")
                                .HasColumnName("periodo_hasta");

                            b1.HasKey("InformeId");

                            b1.ToTable("informe", "reporting");

                            b1.WithOwner()
                                .HasForeignKey("InformeId");
                        });

                    b.OwnsMany("Bep.Modules.Reporting.Domain.VersionInforme", "Versiones", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("CargadoPorSubjectId")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("cargado_por_subject_id");

                            b1.Property<DateTimeOffset>("FechaCargaUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("InformeId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Numero")
                                .HasColumnType("integer");

                            b1.Property<string>("ObjectKey")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("object_key");

                            b1.HasKey("Id");

                            b1.HasIndex("InformeId");

                            b1.ToTable("version_informe", "reporting");

                            b1.WithOwner()
                                .HasForeignKey("InformeId");
                        });

                    b.Navigation("Anexos");

                    b.Navigation("Comentarios");

                    b.Navigation("Periodo")
                        .IsRequired();

                    b.Navigation("Versiones");
                });
#pragma warning restore 612, 618
        }
    }
}
