// <auto-generated />
using System;
using Bep.Modules.Insights.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bep.Modules.Insights.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InsightsDbContext))]
    [Migration("20260615103111_InitialInsights")]
    partial class InitialInsights
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("insights")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bep.Modules.Insights.Domain.AnalisisAmbiental", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampanaId")
                        .HasColumnType("uuid")
                        .HasColumnName("campana_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("GeneradoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generado_utc");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("MotivoDescarte")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("motivo_descarte");

                    b.Property<string>("Resumen")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ValidadoPorSubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("validado_por_subject_id");

                    b.Property<DateTimeOffset?>("ValidadoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validado_utc");

                    b.HasKey("Id");

                    b.HasIndex("CampanaId");

                    b.HasIndex("Estado");

                    b.HasIndex("TenantId");

                    b.ToTable("analisis_ambiental", "insights");
                });

            modelBuilder.Entity("Bep.Modules.Insights.Domain.AnalisisAmbiental", b =>
                {
                    b.OwnsMany("Bep.Modules.Insights.Domain.Hallazgo", "Hallazgos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("AnalisisAmbientalId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Detalle")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<string>("Parametro")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)");

                            b1.Property<string>("Severidad")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.HasKey("Id");

                            b1.HasIndex("AnalisisAmbientalId");

                            b1.ToTable("hallazgo", "insights");

                            b1.WithOwner()
                                .HasForeignKey("AnalisisAmbientalId");
                        });

                    b.Navigation("Hallazgos");
                });
#pragma warning restore 612, 618
        }
    }
}
