// <auto-generated />
using System;
using Bep.Modules.Organization.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bep.Modules.Organization.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrganizationDbContext))]
    partial class OrganizationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("organization")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bep.Modules.Organization.Domain.Centro", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoInterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CodigoInterno")
                        .IsUnique();

                    b.ToTable("centro", "organization");
                });

            modelBuilder.Entity("Bep.Modules.Organization.Domain.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreadaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Rubro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rut");

                    b.HasKey("Id");

                    b.HasIndex("Rut")
                        .IsUnique();

                    b.ToTable("empresa", "organization");
                });

            modelBuilder.Entity("Bep.Modules.Organization.Domain.Centro", b =>
                {
                    b.HasOne("Bep.Modules.Organization.Domain.Empresa", null)
                        .WithMany("Centros")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Bep.Modules.Organization.Domain.CoordenadasGps", "Coordenadas", b1 =>
                        {
                            b1.Property<Guid>("CentroId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitud")
                                .HasColumnType("double precision")
                                .HasColumnName("latitud");

                            b1.Property<double>("Longitud")
                                .HasColumnType("double precision")
                                .HasColumnName("longitud");

                            b1.HasKey("CentroId");

                            b1.ToTable("centro", "organization");

                            b1.WithOwner()
                                .HasForeignKey("CentroId");
                        });

                    b.Navigation("Coordenadas")
                        .IsRequired();
                });

            modelBuilder.Entity("Bep.Modules.Organization.Domain.Empresa", b =>
                {
                    b.Navigation("Centros");
                });
#pragma warning restore 612, 618
        }
    }
}
