// <auto-generated />
using System;
using Bep.Modules.Campaign.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bep.Modules.Campaign.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CampaignDbContext))]
    partial class CampaignDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("campaign")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bep.Modules.Campaign.Domain.Campania", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<Guid[]>("CentroIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("centro_ids");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("TenantId");

                    b.ToTable("campania", "campaign");
                });

            modelBuilder.Entity("Bep.Modules.Campaign.Domain.Campania", b =>
                {
                    b.OwnsOne("Bep.Modules.Campaign.Domain.RangoFechas", "Periodo", b1 =>
                        {
                            b1.Property<Guid>("CampaniaId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("Fin")
                                .HasColumnType("date")
                                .HasColumnName("fecha_fin");

                            b1.Property<DateOnly>("Inicio")
                                .HasColumnType("date")
                                .HasColumnName("fecha_inicio");

                            b1.HasKey("CampaniaId");

                            b1.ToTable("campania", "campaign");

                            b1.WithOwner()
                                .HasForeignKey("CampaniaId");
                        });

                    b.OwnsMany("Bep.Modules.Campaign.Domain.Responsable", "Responsables", b1 =>
                        {
                            b1.Property<Guid>("CampaniaId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Rol")
                                .IsRequired();

                            b1.Property<string>("SubjectId")
                                .IsRequired();

                            b1.HasKey("CampaniaId", "__synthesizedOrdinal");

                            b1.ToTable("campania", "campaign");

                            b1
                                .ToJson("responsables")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CampaniaId");
                        });

                    b.Navigation("Periodo")
                        .IsRequired();

                    b.Navigation("Responsables");
                });
#pragma warning restore 612, 618
        }
    }
}
