// <auto-generated />
using System;
using Bep.Modules.Sampling.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bep.Modules.Sampling.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SamplingDbContext))]
    partial class SamplingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sampling")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bep.Modules.Sampling.Domain.Muestra", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampanaId")
                        .HasColumnType("uuid")
                        .HasColumnName("campana_id");

                    b.Property<Guid>("CentroId")
                        .HasColumnType("uuid")
                        .HasColumnName("centro_id");

                    b.Property<string>("CodigoQr")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("codigo_qr");

                    b.Property<string>("CodigoUnico")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo_unico");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("FechaRegistroUtc")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string[]>("Fotos")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("fotos");

                    b.PrimitiveCollection<string[]>("ParametrosSolicitados")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("parametros_solicitados");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("CampanaId");

                    b.HasIndex("CodigoQr")
                        .IsUnique();

                    b.HasIndex("CodigoUnico")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("muestra", "sampling");
                });

            modelBuilder.Entity("Bep.Modules.Sampling.Domain.Muestra", b =>
                {
                    b.OwnsMany("Bep.Modules.Sampling.Domain.EventoMuestra", "Eventos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Descripcion")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<DateTimeOffset>("FechaUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("MuestraId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<string>("UsuarioSubjectId")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("Id");

                            b1.HasIndex("MuestraId");

                            b1.ToTable("evento_muestra", "sampling");

                            b1.WithOwner()
                                .HasForeignKey("MuestraId");
                        });

                    b.OwnsMany("Bep.Modules.Sampling.Domain.RegistroCustodia", "Custodias", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<bool>("Aceptada")
                                .HasColumnType("boolean");

                            b1.Property<string>("DeSubjectId")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<DateTimeOffset?>("FechaAceptacionUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset>("FechaTransferenciaUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("MuestraId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ParaSubjectId")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("Id");

                            b1.HasIndex("MuestraId");

                            b1.ToTable("registro_custodia", "sampling");

                            b1.WithOwner()
                                .HasForeignKey("MuestraId");
                        });

                    b.OwnsOne("Bep.Modules.Sampling.Domain.UbicacionGps", "Ubicacion", b1 =>
                        {
                            b1.Property<Guid>("MuestraId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitud")
                                .HasColumnType("double precision")
                                .HasColumnName("latitud");

                            b1.Property<double>("Longitud")
                                .HasColumnType("double precision")
                                .HasColumnName("longitud");

                            b1.Property<double?>("PrecisionMetros")
                                .HasColumnType("double precision")
                                .HasColumnName("precision_metros");

                            b1.HasKey("MuestraId");

                            b1.ToTable("muestra", "sampling");

                            b1.WithOwner()
                                .HasForeignKey("MuestraId");
                        });

                    b.Navigation("Custodias");

                    b.Navigation("Eventos");

                    b.Navigation("Ubicacion")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
