// <auto-generated />
using System;
using Bep.Modules.Laboratory.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bep.Modules.Laboratory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LaboratoryDbContext))]
    [Migration("20260615100817_InitialLaboratory")]
    partial class InitialLaboratory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("laboratory")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bep.Modules.Laboratory.Domain.LoteResultados", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ArchivoObjectKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("archivo_object_key");

                    b.Property<Guid>("CampanaId")
                        .HasColumnType("uuid")
                        .HasColumnName("campana_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Laboratorio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("motivo_rechazo");

                    b.Property<DateTimeOffset>("RecibidoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recibido_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("ValidadoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validado_utc");

                    b.HasKey("Id");

                    b.HasIndex("CampanaId");

                    b.HasIndex("Estado");

                    b.HasIndex("TenantId");

                    b.ToTable("lote_resultados", "laboratory");
                });

            modelBuilder.Entity("Bep.Modules.Laboratory.Domain.LoteResultados", b =>
                {
                    b.OwnsMany("Bep.Modules.Laboratory.Domain.ResultadoParametro", "Resultados", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("CodigoMuestra")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("codigo_muestra");

                            b1.Property<Guid>("LoteResultadosId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Metodo")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)");

                            b1.Property<string>("Parametro")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)");

                            b1.Property<double>("Valor")
                                .HasColumnType("double precision");

                            b1.HasKey("Id");

                            b1.HasIndex("CodigoMuestra");

                            b1.HasIndex("LoteResultadosId");

                            b1.ToTable("resultado_parametro", "laboratory");

                            b1.WithOwner()
                                .HasForeignKey("LoteResultadosId");
                        });

                    b.Navigation("Resultados");
                });
#pragma warning restore 612, 618
        }
    }
}
